name: Portfolio Backend

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [22.10.0]
    env:
      PORT: ${{ secrets.PORT }}
      MONGODB_USERNAME: ${{ secrets.MONGODB_USERNAME }}
      MONGODB_PASSWORD: ${{ secrets.MONGODB_PASSWORD }}
      FRONTEND: ${{ secrets.FRONTEND }}

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - name: Change Directory
      run: cd /home/danyal/actions-runner/pfbackend-runner/_work/portfolio-backend/portfolio-backend
    - run: pm2 restart 1 --update-env

